const creatureIconData = {
  id: "creature-icon",
  name: "CREATURE ICON",
  image: "system-data/system-images/creature-icon.png",

  description: `
The **Creature Icon** is small visual representations generated by the Bio-Computer. Each icon has a resolution of 42 × 42 pixels and is designed to provide a quick visual reference for a creature. Due to the limited size and pixel-based format, some icons may appear simplified or slightly irregular. Despite this, they are designed to preserve the most recognizable characteristics of each creature. Icons play an important role within CreatureMatsu, allowing creatures to be identified easily without requiring additional context. They are used throughout the Dex, categories, pillar maps, and other classification systems as a standardized visual reference.
`,

  sections: [
    {
      title: "Icon Dimensions",
      text: `
[img]system-data/system-images/icon-px.png[/img]
`
    },
    {
      title: "Usage and Colors",
      text: `
<p>The Creature Icons are designed around a standard resolution of 42 × 42 pixels. This size serves as the native format generated by the Bio-Computer. Because the original resolution is very small, icons may become difficult to see on larger displays.</p>
<p>To improve visibility, icons are commonly displayed using 2× to 4× scaling. This enlargement only affects the rendering size and preserves the original pixelated appearance without adding new details.</p>
<p>Most icons are surrounded by a border frame, sometimes referred to as a "wall". This frame helps organize specimens within lists, menus, and classification systems. In rare cases, the frame may be omitted to provide additional visual space when displayed on bio-computers, bio-tablets, or analysis screens where information panels appear alongside the icon.</p>
<->
*The comparison of icon scaling dimensions.*
[img]system-data/system-images/icon-number.png[/img]
<->
__Creature icons are normally limited to four mandatory colors:__
◦ **Dark Brown** (#773421) – outlines, shadows, and the darkest visible details.
◦ **Brown** (#A56243) – background areas, negative shapes, and visual illusion elements.
◦ **Yellow** (#EFB775) – mixed-tone areas and intermediate details.
◦ **Light Yellow** (#FFE3C2) – highlights and the brightest visible parts.

<p>Some icons may use an alternative palette, replacing the standard yellow tones with other colors such as blue, green, or different thematic variations. However, the four-color structure remains the same.</p>
<p>The use of background and negative shapes is intentional. In some cases, portions of a creature are suggested through visual illusion rather than direct drawing, allowing recognizable forms to emerge despite the limited pixel count.</p>
<->
*The color palette reference with hexadecimal values.*
[img]system-data/system-images/icon-color.png[/img]
`
    },
    {
      title: "On the Bio-Computer Screen",
      text: `
<p>The screen is designed with a green display used by Dr. Leezar. It is very large, similar to a large television display, allowing creature information, medium-sized text, and icons to be viewed comfortably.</p>
__There are four different icon display modes:__
◦ **CRT-Preview:** A preview version similar to the official icon (Sealed), but without the border wall. It is used to build creature grids and numbered lists.
◦ **CRT-Info:** An enlarged icon used to display information about the creature's appearance alongside its official number and name assigned by Dr. Leezar. It is shown together with saved data and logs in the sidebar. In some cases, visual elements may be adjusted for readability, such as changing the pupil color to a darker shade for better contrast.
◦ **Terminal:** A conceptual display mode that has not yet appeared in the terminal system. Its exact purpose remains unknown.
◦ **Sealed:** The final and official icon. It is used for printing and is stored in Dr. Leezar's folders alongside biological evaluations, analysis reports, and creature records.

[img]system-data/system-images/display-icon.png[/img]
`
    },
    {
      title: "Bio-Computer Terminal Mode",
      text: `
<p>The Bio-Computer terminal mode is used for coding, commands, logs, and driver activation. It does not directly display the final creature icon as a normal visual file.</p>
<p>**Create Icon** is a driver that reads the current DNA data and converts it into an icon. It does not judge the creature’s appearance; it only generates the visual icon based on the DNA information.</p>
<p>After Syndata is completed and the Badge is created, Dr. Leezar may activate an icon driver through the terminal. This driver reads the creature’s current DNA data and begins scanning the icon structure.</p>

__Example process:__
<p></p>
[md]> create Icon
---
Reading DNA...
Identifying specimen...
---
Please select a DNA type: O/K/C/I/J/T
> O
---
Reading DNA data...
Found DNA: Oso
Processing...
Status: Correct
---
Generating profile...
Processing jigsaw parts...
Checking for issues or corrupted data...
Status: OK
---
Scanning icon...
[////////////////////] 100%
---
Icon generated. Ready to display.
[Enter][/md]
The terminal screen works as a command interface, while the final icon appears only after the Bio-Computer finishes interpreting the creature’s DNA.
<p></p>
__Additional notes:__
◦ If the icon scan is not completed, the Bio-Computer may have failed to process the data correctly. In this case, the scan can be attempted again.
◦ Once the icon is generated, it cannot be manually modified. The driver determines how the creature’s appearance and function should be visually represented.
◦ If the wrong Matsu data letter is selected, the status will be marked as incorrect and the process must be restarted.
◦ The “Checking for issues or corrupted data...” step is important. During this process, the coding system verifies the icon structure after the jigsaw parts are processed. This step may take around two additional minutes before the icon is created.
◦ This verification checks visual traits and function-based details before generation.
`
    },
    {
      title: "Icon Types",
      text: `
<p>*— COMING SOON —*</p>
`
    },
    {
      title: "Icon Effects",
      text: `
<p>*— COMING SOON —*</p>
`
    },
    {
      title: "Role in the CreatureMatsu universe",
      text: `
<p>Dr. Leezar uses creature icons to identify and classify each specimen within the Bio-Computer system. In some cases, an icon may also reflect the creature's function, action, or most recognizable trait. The icons serve as official records linked to each creature's file, allowing the Bio-Computer to store coding data, functions, intended uses, biological evaluations, and written logs documented by Dr. Leezar throughout the analysis process.</p>
`
    },
    {
      title: "Trivia",
      text: `
◦ The icons are inspired by the icon style of the [Monster Hunter](https://en.wikipedia.org/wiki/Monster_Hunter) series, particularly their recognizable creature silhouettes and visual identification system. The example from the [MHGen icons](https://monsterhunterwiki.org/wiki/Category:MHGen_Monster_Icons) is similar in its use of poses, and fixed icon boundary dimensions.
`
    }
  ]
};
