const secondPillarChoro = [
// ==================================================
// 🟢 JUMPCHORO ====================================
// ==================================================
    {
  "id": "055",
  "name": "JUMPCHORO",
  "matsu": "choro",
  "category": "CHORO VARIATIONS",
  "pillar": "VARIATIONS",
  "size": "",
  "image": "c055.png",
  "icon": "icon_055.png",
  "drDescription": "His body resembles a frog, allowing him to leap higher than a two-story house!",
  "description": "Jumpchoro is a frog-like creature with a recognizable Matsu head. His powerful hind legs allow him to jump up to approximately 8 meters (26 feet) into the air, making him one of the highest jumpers among the CreatureMatsu.<2br>\nHe often assists with rescue and retrieval tasks that would normally require climbing. He can leap into tall trees to recover a child’s lost balloon, reach rooftops to retrieve a baseball, or access elevated places that are difficult for others to reach. Despite his incredible jumping ability, he performs these tasks calmly and carefully, making him a reliable helper whenever something ends up far above the ground.",
  "functionText": "Jumpchoro’s legs are specialized for powerful spring-like jumping. Before leaping, he bends his hind legs and stretches a large tendon inside them. This tendon absorbs the force generated by his muscles and stores it like an elastic band or a compressed spring.<2br>\nWhen released, this stored energy launches Jumpchoro upward with extreme force. His jump can reach approximately 8 meters (26 feet) in height, with a maximum forward distance of about 4 meters (13 feet) in a single leap. The power of his two hind legs works similarly to the jumping mechanism of a cricket, allowing him to reach high places quickly and efficiently.",
  "nameOrigin": "“**Jumpchoro**” combines “**jump**” and “**Choro**,” his Matsu base. The name reflects a living jumper who launches himself toward the sky.<2br>\nHowever, his brothers gave him the nickname “**Chorofrog**” because of his frog-like Choro face. It is used more like a teasing insult than an official name.",
  "generalOrigin": "• Jumpchoro is based on [frogs](https://en.wikipedia.org/wiki/Frog), animals capable of jumping great distances thanks to their long, muscular hind legs. These legs often form a Z-like shape, functioning like natural springs before launching the body forward or upward.\n• His tail is also inspired by [tailed frogs](https://en.wikipedia.org/wiki/Tailed_frog) from the genus *Ascaphus*. However, unlike real frogs, Jumpchoro has a long neck. In his case, this does not create physical risk during jumping, because his body was adapted specifically for that movement.\n• Jumpchoro usually prefers standing on two legs, giving him a more [anthropomorphic](https://en.wikipedia.org/wiki/Anthropomorphism) appearance. This does not fully match the natural body structure of real frogs. In nature, a frog’s front legs mostly act as [shock absorbers](https://en.wikipedia.org/wiki/Shock_absorber) during landing, while the hind legs provide the main jumping force. When a frog jumps or swims, the femur, tibia, and tarsus extend into a straight line, briefly resembling the shape of human legs.\n• Many movies and animations show frogs standing like humans, but that is mostly a visual myth rather than natural frog behavior. Jumpchoro is different: he is not a “pure frog,” but a CreatureMatsu with a frog-based body... adapted for a different biological function.",
  "reference": "-    Choromatsu is visually remembered as the Matsu most closely associated with a cute **frog-like image**, especially because of his green color and his iconic V-shaped mouth.\n-    This connection appears in several official and game-related designs. In the [Sanrio collab](https://osmt.fandom.com/wiki/Sanrio_Characters), Choro was paired with [Keroppi](https://hellokitty.fandom.com/wiki/Kerokerokeroppi). In [Grimm Matsu](https://osmt.fandom.com/wiki/Grimm_Matsu), he was dressed as the [Frog Prince](https://en.wikipedia.org/wiki/The_Frog_Prince). In the *Hesokuri Wars*: [Animal Pajamas](https://osmt.fandom.com/wiki/Animal_Pajamas) set, he wore a frog [kigurumi](https://en.wikipedia.org/wiki/Costumed_performer#In_Japan) and in the [Raincoat](https://osmt.fandom.com/wiki/Raincoat) set, he carried a frog-shaped [teru teru bōzu](https://en.wikipedia.org/wiki/Teru_teru_bōzu) beneath his umbrella. Because of these repeated associations, Jumpchoro takes that long-running frog imagery and turns it into a full biological transformation.",
  "trivia": "",
  "extras": {
    "status": "U",
    "code": "frog",
    "responsible": "",
    "description": "Late one night, while Dr. Leezar’s family was asleep, mysterious silhouettes entered the laboratory. Someone activated the Bio-Computer and typed the code `frog`.<2br>\nThe following morning, Dr. Leezar woke up and was surprised to find a new Choro Badge beside the Bio-Computer. As he analyzed the system in confusion, he discovered an unusual creation code: `frog`. The Sextuplets were equally surprised, while Choromatsu was completely confused about who had nominated him. It almost felt as if the Bio-Computer itself had played a prank on him, making the entire situation highly suspicious. After the transformation test, **Jumpchoro** **was born**.<2br>\nScratching his head, Dr. Leezar muttered,\n> *“Could this be another malfunction... just like the Squiangso case?”*\nOso simply shrugged.\n> *“That’s strange... we have no idea.”*\nJumpchoro looked at Oso suspiciously before turning to Dr. Leezar,\n> *“Am I really a frog? Is it because I can jump?”*\nDr. Leezar replied,\n> *“I’m not sure... maybe the Bio-Computer activated the automatic driver?”*\n<p>He sat back down in front of the monitor and continued investigating. The system eventually displayed a suggested purpose: “Jumping assistance for retrieval missions.” After reviewing the results, Dr. Leezar officially named the creature Jumpchoro.</p>\n<->\nStill confused about the reason behind his powerful jumping ability, Jumpchoro asked why such a function was necessary. Dr. Leezar smiled and answered,\n> *“It sounds very useful for helping others. Let’s examine your legs outside in the yard.”*\nJumpchoro blinked.\n> *“Wait... what?”*\n<->\n<p>The event of that first day left everyone uncertain. They believed the Bio-Computer had experienced another strange malfunction, yet it also hinted at the existence of a hidden feature: an “automatic recommendation algorithm based on biological functions.” The unusual code `frog` may not have been random at all, but an important technical suggestion chosen to evaluate the creature’s jumping ability.</p>\nThe only question that remained was... Would the [next creature](056) return to normal... or would another mysterious creation appear?",
    "action": [
      "A055-A.png",
      "A055-B.png"
    ],
    "sheet": "",
    "log": "",
    "past": "> [color=#EFB775]“Since **Jumpchoro** is based on a green frog, it also reflects a small part of my own history. When **I first became a fan of Osomatsu-san**, my second online username was[/color] [m3]GreenFrogKP[/m3][color=#EFB775].[/color] [color=#EFB775]Nowadays, I simply go by[/color] [m3]Frog[/m3] [color=#EFB775]or Froggy.”[/color]",
    "funFact": "If Jumpchoro is relaxing and a leaf gently lands on his tail, he suddenly wakes up in surprise and instinctively leaps high into the sky.",
    "firstExperiment": ""
  },
  "protocol": {
    "entries": [],
    "safety": "MISCHIEVOUS"
  }
},

// ==================================================
// 🟢 CHORYRUS =====================================
// ==================================================
  {
  "id": "056",
  "name": "CHORYRUS",
  "matsu": "choro",
  "category": "CHORO VARIATIONS",
  "pillar": "VARIATIONS",
  "size": "",
  "image": "c056.png",
  "icon": "icon_056.png",
  "drDescription": "A living mummy covered in ancient paper. He uses his strong papers for combat, wrapping anyone who gets caught by them.",
  "description": "Choryrus has the appearance of a mummy, although he is not actually a zombie. His body is covered in old paper-like layers, giving him an ancient and preserved look. His arms and tail are made of “living papers,” flexible sheets that can stretch, grab, wrap, and restrain others without tearing apart. These papers act like functional extensions of his body, allowing him to fight or capture targets by binding them tightly. For some reason, his face originally looked cold and emotionless, but this ended up fitting his mummy-like appearance even better.",
  "functionText": "Choryrus’ living papers are one of the most surprising biological phenomena among the CreatureMatsu. Although they resemble aged paper or ancient parchment, they are actually living keratinized sheets connected to a living biological base. They are dry, lightweight, flexible, and highly resistant to tearing. These living papers can extend up to 3 meters (9.8 feet), roll up like sheets of paper, wrap around objects or creatures, restrain targets, deliver slap-like strikes, and constrict without tearing.<2br>\nTheir outer surface is composed of keratinized tissue, which is why it does not bleed if scratched. Movement originates from the living base through motor control, allowing the sheets to extend, bend, curl, and pull with precision. They can sense touch, pressure, and tension, but they cannot feel pain or temperature through their paper-like surface.",
  "nameOrigin": "“**Choryrus**” combines “**Choro**,” his Matsu base, with “**papyrus**,” referring to ancient paper. The name reflects his body being covered in worn, deteriorated paper-like layers, giving him the appearance of a mummy.",
  "generalOrigin": "• Choryrus is based on an [Egyptian mummy](https://en.wikipedia.org/wiki/Mummy#Egyptian_mummies), the preserved body of a human or animal intentionally prepared through embalming techniques such as wrapping and mummification, especially associated with ancient Egypt.\n• However, Choryrus is not wrapped in modern paper. His “ancient papers” are closer to [papyrus](https://en.wikipedia.org/wiki/Papyrus), a writing material made in ancient Egypt from the stems of the aquatic plant *Cyperus papyrus*, which grew along the banks of the Nile River.\n• Choryrus’ cold-looking face, partially hidden beneath layers of paper, gives him the unsettling presence of a mummy or zombie, as if he had “lost his soul.” However, when he covers his head with paper to the point of hiding most of his face, it is mainly interpreted as an act of voluntary isolation and self-protection. This behavior stems from social discomfort and shame, caused by a possible trolling incident that humiliated his private life. This is explained further in [link:The Suspect of Creation:status:generalOrigin].",
  "reference": "• Choryrus is inspired by one of Choromatsu’s most iconic jokes from an [color=#F7CC9B]official anthology[/color]. While sitting on the toilet, he faces a terrifying situation: there is no toilet paper left. Trapped in the bathroom, he desperately calls for help from the rest of the household. However, instead of bringing him toilet paper, someone hands him an unusual object to clean himself with: a slice of toasted bread.\n• Although the original source of this illustration is currently [color=#F7CC9B]unknown[/color], it remains one of the more bizarre and crude jokes associated with Choromatsu, eventually inspiring Choryrus’ paper-themed concept.",
  "trivia": "",
  "extras": {
    "status": "U",
    "code": "paper",
    "responsible": "",
    "description": "A few days after the Jumpchoro incident, mysterious silhouettes once again entered the laboratory during the night. They activated the Bio-Computer and entered the code `paper`.<2br>\nThe following morning, Dr. Leezar woke up to discover yet another new Choro Badge beside the Bio-Computer. As he examined the system, he found the suspicious code: `paper`. He frowned in confusion.\n> *“Paper... for what?”*\nMeanwhile, Choro was already in shock for a completely different reason. Embarrassed by one of his most awkward daily habits: sitting on the toilet and constantly asking for toilet paper, he could only stare in disbelief. After the transformation experiment, **Choryrus** **was born**. Unlike the previous case, Dr. Leezar began to doubt that this was simply another hidden biological recommendation algorithm like the one suspected in Jumpchoro’s creation. Instead, he considered a far more worrying possibility: someone might be “[color=#F7CC9B]hacking[/color]” the Bio-Computer. Concerned that its data could be compromised, he immediately began searching the system for any signs of unauthorized access. With his usual cold expression,<2br>\nChoryrus looked at Dr. Leezar and quietly asked,\n> *“Am I really a mummy?”*\nOso casually replied,\n> *“Ye. You’re covered in paper so ya won’t get cold~”*\nInstantly, Choryrus grabbed Oso by the collar and shouted,\n> *“THAT’S NOT WHAT I MEANT! DO I REALLY LOOK LIKE A MUMMY?!”*\n<p>\nThis second incident made everyone even more uneasy. What had first seemed like a possible system malfunction was now beginning to resemble something far more dangerous, a possible hack using random code words such as `paper`. Even so, Choryrus’ remarkable living papers proved to be an extraordinary biological function. But at that moment, the laboratory was filled with concern rather than excitement.</p>\n...What would [happen next](057)?",
    "action": [
      "A056-A.png",
      "A056-B.png"
    ],
    "sheet": "",
    "log": "",
    "past": "",
    "funFact": "When Choryrus crouches in front of his brothers and Dr. Leezar, his cold face and suffering expression make him look terrifying. But then Jyushi suddenly grabs one of his papers and pulls it. Choryrus spins around rapidly as the paper unwraps from his body, until he looks almost completely naked. Shocked and embarrassed, he covers himself between his legs with his living-paper arms, his eyes wide open, before running away to hide somewhere.",
    "firstExperiment": ""
  },
  "protocol": {
    "entries": [],
    "safety": "MISCHIEVOUS"
  }
},

// ==================================================
// 🟢 MR. CHOREYES =================================
// ==================================================  
  {
  "id": "057",
  "name": "MR. CHOREYES",
  "matsu": "choro",
  "category": "CHORO VARIATIONS",
  "pillar": "VARIATIONS",
  "size": "",
  "image": "c057.png",
  "icon": "icon_057.png",
  "drDescription": "He has many eyes, and his vision is impossible for us to understand. His eyes can see anyone, and he conceals people’s secret lives.",
  "description": "Mr. Choreyes is one of the most shocking creatures created during the experiment. His body is covered with many eyes across almost every part of him, creating an unsettling presence that even Dr. Leezar’s family finds difficult to face. His countless eyes function almost like security cameras, watching people from multiple directions at once. Because of this, he is connected to one of the most dramatic and suspicious events in Choro Variations: a creature born from vision, surveillance, and the hidden private lives of others.",
  "functionText": "Mr. Choreyes is unusual because of the large number of eyes covering his body. It is not fully understood how his vision works, but he once described it as:\n> *“I can see everything… and it gives me a headache.”*\nThis does not follow normal biological vision. Having so many eyes likely sends too many visual images into his brain at once, causing dizziness, sensory overload, and intense discomfort.<2br>\nWhen his eyes “awaken,” they send their vision toward a dimensional surface, allowing him to watch certain people from a distance. This makes him function almost like a living surveillance system, constantly observing and following a target with his many eyes. However, being watched by Mr. Choreyes can make the observed person feel paranoid and deeply uncomfortable, as if the whole world were staring at them. He often sits silently like a lurker in front of someone, watching without moving.<2br>\nHis biggest weakness is the suffering caused by his own vision. The overwhelming amount of visual information makes him dizzy, tired, and visually disturbing to others. Because of this, Dr. Leezar often tells him that he needs to *“close his eyes and relax.”*",
  "nameOrigin": "“**Mr. Choreyes**” combines “**Choro**,” his Matsu base, with “**eyes**,” referring to the many eyes covering almost his entire body. The mandatory “**Mr.**” was added to give him a more formal and respectful identity. The name reflects a creature whose body exaggerates the act of looking in every direction at once.<2br>\nHis original name was simply “**Choreyes**.” However, after the creature became discouraged by the difficult moment caused by his own creation incident, Dr. Leezar added “**Mr.**” to his name as a sign of respect.",
  "generalOrigin": "• Mr. Choreyes is based on three yōkai: [Mokumokuren](https://en.wikipedia.org/wiki/Mokumokuren), [Hyakume](https://www.curiousordinary.com/2022/10/hyakume.html), and especially [Dodomeki](https://en.wikipedia.org/wiki/Dodomeki). He combines visual elements from all three:\n▪ __[color=#F7CC9B]Mokumokuren:[/color]__ reflected in the floating eyes around Mr. Choreyes.\n▪ __[color=#F7CC9B]Hyakume:[/color]__ reflected in the many eyes covering his tail.\n▪ __[color=#F7CC9B]Dodomeki:[/color]__ reflected in the eyes located on each of Mr. Choreyes’ arms.\n• His appearance has a subtle [ogre](https://en.wikipedia.org/wiki/Ogre)-like influence, combining a robust body with old green skin, visible canine teeth, freckles, and a bitter expression. Despite this, he is only slightly larger than a base Matsu, giving him a unique rather than gigantic appearance. Calling someone an “ogre” can suggest a bitter, isolated person who prefers solitude. Because of his frightening body and unsettling appearance, Mr. Choreyes feels guilty and sad, as if his own existence makes others uncomfortable.\n• Mr. Choreyes’ many watchful eyes are also inspired by [CCTV control centers](https://en.wikipedia.org/wiki/Closed-circuit_television) found in large offices and security facilities, where dozens of live camera feeds are displayed on multiple monitors at the same time. Like a [surveillance](https://en.wikipedia.org/wiki/Surveillance) operator constantly watching every screen, Mr. Choreyes continuously observes everything around him. However, just as monitoring too many screens for long periods can cause [eye strain](https://en.wikipedia.org/wiki/Eye_strain) and mental fatigue, his overwhelming vision often leaves him exhausted and suffering from headaches.",
  "reference": "-  Mr. Choreyes is based on the popular and iconic [Choromatsu Dodomeki](https://64.media.tumblr.com/826f10063ec925d06d29010fd3ac10b7/5302d8174864c6aa-9d/s540x810/51e6653d6e8e54f13537fd9967938a9632f63e1a.pnj), featured in a pin-up poster from *Osomatsu Character Book #6*. This design inspired a large amount of fanart during the early era of *Osomatsu-san*, thanks to its gothic and mysterious aesthetic that fascinated many artists and content creators. \n-  Choromatsu’s self-criticism often revolves around his constant [hypocrisy](https://en.wikipedia.org/wiki/Hypocrisy). Although he presents himself as the most mature, rational, and responsible brother, he still hides deep insecurities. In Mr. Choreyes’ case, Choro urgently asked for a creature with stronger surveillance power to watch over his brothers. However, the result went wrong: Mr. Choreyes suffered because his creation did not move forward in a healthy way, turning Choro’s request into the opposite of what he wanted.",
  "trivia": "Mr. Choreyes was the second creature I drew for the Second Pillar, following [Seguara](049).",
  "extras": {
    "status": "U",
    "code": "stare",
    "responsible": "Choro (anger), **Oso and Jyushi (suspected cases)**",
    "description": "Several days later, while everyone was asleep, something unusual happened once again. Inside the Sextuplets’ bedroom, **Kara** heard faint voices during the night. He quietly opened one eye and noticed that something suspicious was happening.<2br>\nThe following morning, Choro and Todo woke up to find **Oso and Jyushi** peacefully sleeping near the bedroom door, tied together with strings. During breakfast, Choro brought up the strange incident while Kara and Ichi were eating sandwiches.\nKara calmly replied,\n> *“Those idiots probably sneaked into the lab again.”*\nHe then revealed that **Oso and Jyushi had secretly entered the laboratory during the night and used the Bio-Computer without permission**. Choro immediately turned red with anger and rushed to Dr. Leezar, demanding a creature capable of watching his foolish brothers at all times.<2br>\nFeeling rushed and flustered, Dr. Leezar nervously entered the code `stare` into the Bio-Computer. However, the Bio-Computer interpreted the command far too literally, creating a body covered with countless eyes to maximize constant observation. A few hours after Choro’s desperate request, the Badge was completed. Choro immediately grabbed it and transformed into **Mr. Choreyes**, not caring what his creature form might look like. He then left the laboratory to begin watching his brothers. Meanwhile, Dr. Leezar sat in the corner of the laboratory, hugging his own legs in deep concern, carefully keeping his distance from Choro’s anger.<2br>\nAfter several hours of surveillance, Mr. Choreyes eventually broke down in tears. With his countless eyes crying at once, he isolated himself in the bathroom. Louise entered and was shocked to find him blaming himself for his own appearance.\n> *“It’s all mah fault... I have so much anxiety... and mah head hurts.”*\nLouise knelt beside him and gently comforted him.\n> *“None of this is your fault. You have a very kind heart.”*\nSoon afterward, Dr. Leezar found Mr. Choreyes in the same miserable state. He carefully lifted the exhausted creature into his arms and quietly said,\n> *“You’re not ugly... you’re simply more unique.”*\n<p>Mr. Choreyes fell silent… He then confessed that Oso and Jyushi had deliberately entered those codes to humiliate Choro, leaving Dr. Leezar completely shocked.</p>\n<p>At that moment, Dr. Leezar realized something he had completely overlooked: the Bio-Computer had never been protected with a password. For the first time since its creation, he secured the system.<2br>\nAs punishment, Oso and Jyushi were grounded for an entire week. They were forbidden from enjoying their hobbies, playing games, watching television, or transforming into creatures. Instead, they spent their days doing household chores and living an unusually boring routine.<2br>\nThis incident later became known as “**The Tragedy of Choro**.” First came [Jumpchoro](055), created from the frog-related teasing directed at Choro; then came [Choryrus](056), inspired by the joke about constantly asking for toilet paper; finally came **Mr. Choreyes**, born from Choro’s angry request to keep watch over his brothers. Although Oso and Jyushi were ultimately responsible for provoking these events by bullying Choro and misusing the Bio-Computer, Dr. Leezar also recognized his own mistake in leaving the system unprotected.<2br>\nUnfortunately, these unstable creatures could not simply be recreated. Their creation codes had to be preserved as permanent records. While they remained fascinating biological discoveries to Dr. Leezar, they were far from ideal outcomes for Choro.</p>",
    "action": [
      "A057-A.png",
      "A057-B.png"
    ],
    "sheet": "",
    "log": "",
    "past": "",
    "funFact": "Mr. Choreyes often sits alone in a corner, staring coldly at his favorite little book with his many eyes, making sure no one comes close enough to steal it. No one really knows what happened inside him after all that suffering.",
    "firstExperiment": ""
  },
  "protocol": {
    "entries": [],
    "safety": "MISCHIEVOUS"
  }
},

// ==================================================
// 🟢 THORNSPHORO ===================================
// ==================================================
  {
  "id": "058",
  "name": "THORNSPHORO",
  "matsu": "choro",
  "category": "CHORO VARIATIONS",
  "pillar": "VARIATIONS",
  "size": "",
  "image": "c058.png",
  "icon": "icon_058.png",
  "drDescription": "His body is covered with spikes whenever he enters a defensive posture. As his tail rapidly draws in air, his body inflates into a large spiny sphere.",
  "description": "Thornsphoro resembles a porcupinefish. In his normal state, his body remains deflated, giving him a wrinkled appearance with his spikes hanging downward. However, when he becomes frightened or angry, his tail rapidly draws in air, causing his body to inflate into a spherical shape while his spikes stand upright, making him much more difficult to approach.",
  "functionText": "Thornsphoro’s body functions much like a balloon. In his deflated state, there is very little air beneath the skin, causing his body to appear wrinkled with loose, hanging spikes. When he inflates, his tail acts like a biological air pump, rapidly drawing air into his body until it expands into a rigid sphere. As the skin stretches, the spikes become fully extended, creating an effective defensive mechanism against predators or threats. When he deflates, his tail releases the stored air, gradually reducing his body back to its wrinkled form.<2br>\nAs his body becomes nearly spherical when inflated, his legs spread slightly apart to provide a wider base of support. This adaptation improves his stability and helps distribute his weight more effectively while moving. Despite this, balancing such a large inflated body is not always easy, and he can still be clumsy, occasionally losing his footing and rolling onto the ground before regaining his balance.",
  "nameOrigin": "“**Thornsphoro**” combines “**thorn**,” “**sphere**,” and “**Choro**,” his Matsu base. The name reflects his defensive transformation into a large, spiked sphere.",
  "generalOrigin": "• Thornsphoro is based on the [porcupinefish](https://en.wikipedia.org/wiki/Porcupinefish), which uses inflation as a defensive mechanism, much like a pufferfish. Unlike many other fish, porcupinefish do not have a rigid rib cage, giving their bodies extreme flexibility. They can rapidly swallow large amounts of water, or air when outside the water, into an elastic stomach, expanding to roughly three or four times their normal size to make themselves harder to swallow.\n• Thornsphoro’s body shape, from his main body to his tail, strongly resembles a [toy balloon](https://en.wikipedia.org/wiki/Toy_balloon), especially a [color=#F7CC9B]jumbo balloon[/color], particularly when his body becomes deflated. His tail works like a balloon nozzle, allowing air to be blown into his body so he can inflate. Although his entire body is covered in thorns, another part of his concept is inspired by a [flail](https://en.wikipedia.org/wiki/Flail_(weapon)). If someone grabs his tail and swings him around wildly, his inflated body behaves like the weighted head of the weapon. However, unlike a real flail, his body remains relatively lightweight because it is mostly filled with air.\n• Thornsphoro’s tail acts as a biological [air pump](https://en.wikipedia.org/wiki/Air_pump). His long tail ends in a “beak” that opens to draw in air and closes tightly like a valve to prevent it from escaping. Inside the tail, specialized lungs use a mechanism similar to [buccal pumping](https://en.wikipedia.org/wiki/Buccal_pumping), repeatedly inhaling air until his entire body is fully inflated and his spines become rigid. Once inflation is complete, the beak remains sealed without requiring constant muscular effort, allowing him to maintain his defensive form.",
  "reference": "This creature does not have a direct reference to *Osomatsu-san*.",
  "trivia": "",
  "extras": {
    "status": "S",
    "code": "spike",
    "responsible": "None. Everything went well.",
    "description": "",
    "action": [
      "A058-A.png",
      "A058-B.png"
    ],
    "sheet": [
      {
        "src": "thornsphoro.png",
        "caption": "Concept art of Thornsphoro – Full Body & Detail Sheet."
      }
    ],
    "log": "",
    "past": "",
    "funFact": "When Thornsphoro is fully inflated, his Choro face takes on an angry expression as he stares intensely at someone like a threat. His little legs take slow, careful tap-tap steps to keep his enormous spherical body balanced. However, if someone pushes him and he falls onto the ground, his inflated body makes a tiny boing.",
    "firstExperiment": ""
  },
  "protocol": {
    "entries": [],
    "safety": "CAUTION"
  }
},

// ==================================================
// 🟢 SILKHORO =====================================
// ==================================================
  {
  "id": "059",
  "name": "SILKHORO",
  "matsu": "choro",
  "category": "CHORO VARIATIONS",
  "pillar": "VARIATIONS",
  "size": "",
  "image": "c059.png",
  "icon": "icon_059.png",
  "drDescription": "Proudly acting like a grandmother, he sometimes weaves warm clothing from the differently colored silk produced by his tail.",
  "description": "Silkhoro is a caterpillar-like creature whose long body gives him a soft and gentle appearance. He proudly takes on the role of a grandmother, using two knitting needles to weave sweaters and other warm garments from the silk produced by his tail. His silk can appear in many different colors, allowing him to create clothing for creatures and their Matsu bases. This makes him especially helpful during winter, since he can produce warm clothes quickly and free of charge. He always seems deeply satisfied when someone wears something he made.",
  "functionText": "Silkhoro’s tail produces silk thread through specialized silk glands. Unlike the silk of a real silkworm, his material is a unique substance known as “**wool-silk**.” It is secreted from the tip of his tail and combines the strength of natural silk with the softness and warmth of wool. Before the wool-silk is released, Silkhoro can change its color inside his tail. Specialized pigment chambers dye the material almost instantly, allowing the thread to emerge in any selected color and dry within only a second. He can also adjust its thickness by controlling the silk glands, wrapping several finer strands together to create thicker yarn when needed.<2br>\nSilkhoro’s brain has also developed a special weaving technique known as “[color=#F7CC9B]Grandma Knitter[/color].” Once he imagines the design of a garment, this neural function sends automatic motor instructions to his arms, allowing him to knit rapidly and almost instinctively with his two knitting needles. While weaving, Silkhoro’s face becomes calm and deeply satisfied, showing pride in the clothing he creates. This behavior is not part of Choro’s usual personality; in this form, he acts more like a caring “[m3]Mama Choro[/m3].”",
  "nameOrigin": "“**Silkhoro**” combines “**silk**” and “**Choro**,” his Matsu base. The name reflects a large caterpillar-like creature who can skillfully weave almost anything he imagines.",
  "generalOrigin": "• Silkhoro is based on the [silkworm](https://en.wikipedia.org/wiki/Bombyx_mori), the caterpillar stage of the silk moth. It is famous for producing a continuous strand of natural [silk](https://en.wikipedia.org/wiki/Silk), a valuable textile fiber that has been used since ancient times. Silk is a natural protein fiber produced from a viscous liquid secreted by specialized glands. Silkhoro’s tail contains [color=#F7CC9B]silk glands[/color], specialized organs similar to those found in silkworms and spiders. These glands secrete a protein-rich fluid that rapidly solidifies when exposed to air, forming a fine, flexible, and remarkably strong thread.\n• Silkhoro’s personality is inspired by [grandmothers who love knitting](https://www.csmonitor.com/1996/0111/11172.html). Their skill comes from years of constant practice, techniques perfected through repetition, and above all, the patience and love they put into every stitch. For them, [knitting](https://en.wikipedia.org/wiki/Knitting) is more than a craft. It is a way of expressing affection and a symbol of perseverance. Every sweater, scarf, or blanket they create represents countless hours spent making something warm and meaningful for someone they care about.\n• Silkhoro’s antennae are unique, as they can curl into spirals to hold two [knitting needles](https://en.wikipedia.org/wiki/Knitting_needle) without losing them. These were inspired by [hair sticks](https://en.wikipedia.org/wiki/Hair_stick), long, rigid hair accessories traditionally used to secure hairstyles. In modern fashion, hair sticks can also complement a casual chic look, blending relaxed clothing with subtle elegance.",
  "reference": "Silkhoro is connected to the affectionate nickname “[m3]Mama Choromatsu[/m3],” a fan interpretation that became popular because of Choromatsu’s behavior and role among his brothers.\n• [color=#F7CC9B]**__The Voice of Reason:__**[/color] Among the six Matsuno brothers, Choromatsu is usually the one who tries to behave maturely, looks for real work, and worries about their future.\n• **__Caring Behavior:__** In several situations, he scolds his brothers for their reckless actions, helps clean up the messes they create, and tries to maintain order in the household, taking on a role that can feel almost maternal.\n• **__Comics and Fanfiction:__** In fan-created content and alternate universes, this protective attitude is often exaggerated. Choromatsu is sometimes portrayed literally as “the mother of the group,” constantly dealing with the chaos caused by his five NEET brothers. <2br>\nSilkhoro transforms that fan interpretation into a gentle biological trait. His knitting, patience, and desire to keep others warm reflect the caring side associated with “Mama Choromatsu.”",
  "trivia": "",
  "extras": {
    "status": "S",
    "code": "knit",
    "responsible": "None. Everything went well.",
    "description": "",
    "action": [
      "A059-A.png",
      "A059-B.png"
    ],
    "sheet": "",
    "log": "",
    "past": "> **Silkhoro’s centauroid body** was inspired by [m1]**Caterneets**[/m1], one of my most beloved AUs and one of the most popular within the Osomatsu-san community.",
    "funFact": "<p>When Oso puts on a sweater the wrong way around, pulling it over his head, he laughs and says,</p>\n\n> <p>*“Ya made the sweater wrong! Hahaha~!”*</p>\n<p> Silkhoro immediately gets angry, pulls the sweater off him, and gives his brother a light bonk on the head with one of his knitting needles, saying,</p>\n\n> <p>*“Stop doing silly things.”*</p>",
    "firstExperiment": ""
  },
  "protocol": {
    "entries": [],
    "safety": "SAFE"
  }
},

// ==================================================
// 🟢 MINTELECH ====================================
// ==================================================  
  {
  "id": "060",
  "name": "MINTELECH",
  "matsu": "choro",
  "category": "CHORO VARIATIONS",
  "pillar": "VARIATIONS",
  "size": "",
  "image": "c060.png",
  "icon": "icon_060.png",
  "drDescription": "He resembles a friendly three-eyed alien. His telekinetic ability allows him to move objects, animals, or people.",
  "description": "Mintelech is an unusual but friendly-looking alien creature with six tentacles and three eyes. His main ability is telekinesis, allowing him to lift, move, or throw objects, animals, and people without physically touching them. His third eye is known as the “Mind Eye.” It allows him to expand his perception beyond normal vision and connect with another dimension, giving him access to powerful psychic abilities such as telekinesis.",
  "functionText": "Mintelech’s head is unusually large, providing enough internal space for his third eye and the neural structures required for telekinesis. When this ability is activated, his third eye opens and connects his mind to a dimensional field, allowing him to seize a nearby object or person without physical contact.<2br>\nThrough this field, he can levitate, move, bend, or throw his target with controlled psychic force. To begin concentrating, two of his tentacles press against the sides of his head, helping him focus his brain and third eye. The stronger or heavier the target is, the more concentration he requires.",
  "nameOrigin": "“**Mintelech**” combines “**mind**,” “**mint**” for the color of his body, “**tele**” from *telekinesis* or the idea of acting from a distance, and the final “**ch**” from “**Choro**,” his Matsu base. The name reflects his psychic ability to move and manipulate objects through the power of his mind.",
  "generalOrigin": "- Mintelech is based on the iconic image of a [Martian-like extraterrestrial](https://en.wikipedia.org/wiki/Mars_in_fiction#Life_on_Mars), often portrayed with green skin and long tentacles in classic science-fiction films, video games, and merchandise. Telepathic and telekinetic powers are also commonly associated with aliens portrayed as highly intelligent beings who use advanced technology or biology. \n- His main ability is [telekinesis](https://en.wikipedia.org/wiki/Telekinesis), the supposed psychic power to move, manipulate, or alter physical objects from a distance using only the [mind](https://en.wikipedia.org/wiki/Mind) and without direct physical contact. His [third eye](https://en.wikipedia.org/wiki/Third_eye) is inspired by spiritual beliefs in which awakening the “mind’s eye” is associated with expanded intuition, inner wisdom, and mental clarity. \n- [Telepathy](https://en.wikipedia.org/wiki/Telepathy) and telekinesis are two different supposed psychic phenomena. Telepathy refers to the transfer of information between minds, while telekinesis, also called psychokinesis, refers to physically manipulating objects or matter without touching them.<2br>\nMintelech uses only telekinesis. However, the creation code `mind` combined several themes, including psychology, spirituality, science fiction, and psychic power. Because of this, his third eye and telekinesis form a complete psychic system: the third eye acts as the guiding mechanism, while telekinesis serves as his physical power.",
  "reference": "Choromatsu is widely regarded as the most intelligent, analytical, and mature of the Sextuplets. However, his intelligence is not always perfect, and his attempts to act rationally can still lead to clumsy or ridiculous situations. Mintelech reflects this contrast by turning Choro’s intelligence into a powerful psychic ability, while still preserving the possibility that his concentration or decisions may fail in unexpectedly awkward ways.",
  "trivia": "",
  "extras": {
    "status": "S",
    "code": "mind",
    "responsible": "None. Everything went well.",
    "description": "",
    "action": [
      "A060-A.png",
      "A060-B.png"
    ],
    "sheet": [
      {
        "src": "mintelech.png",
        "caption": "Concept art of Mintelech – Full Body & Detail Sheet."
      }
    ],
    "log": "",
    "past": "",
    "funFact": "While Mintelech is sweating nervously and concentrating as hard as he can, he struggles to make a single spoon float. Just then, Louise walks in and asks,\n> *“What are you doing?”*\n<p>Without taking his eyes off the spoon, Mintelech quietly replies,</p>\n\n> <p>*“...G-Give me-uh a minute.”*</p>\n...The spoon still refuses to bend.",
    "firstExperiment": ""
  },
  "protocol": {
    "entries": [],
    "safety": "MISCHIEVOUS"
  }
}
];
